version: "3.8"
services:

    frontend:
        build:
            context: ./frontend
        ports:
            - "8080:80"
        depends_on:
            - backend_intellisense
            - backend_executor

    backend_intellisense:
        build:
            context: ./backend/intellisense
            dockerfile: Dockerfile
        env_file:
            - ./backend/intellisense/settings.env
        ports:
            - "8081:80"

    backend_executor:
        build:
            context: ./backend/executor
            dockerfile: Dockerfile
        env_file:
            - ./backend/executor/settings.env
        ports:
            - "8082:80"

    backend_intellisense_tests:
        build:
            context: ./backend/intellisense
            dockerfile: DockerfileTests
        env_file:
            - ./backend/intellisense/settings.env

    backend_executor_tests:
        build:
            context: ./backend/executor
            dockerfile: DockerfileTests
        env_file:
            - ./backend/executor/settings.env
